### ISSUE TITLE
新的 Playlist 协作方式 - Google Sheet

### ISSUE THREAD

**Issue by Deardrops** [jim60105/Playlists#7]
手写 json 维护 Playlist 的方式过于原始，建议创建一个共享的 Google Sheet 维护所有 Playlist。
Google Sheet 非常适合多人协作，编辑起来也很方便。

可以采用以下两种工作流程（Workflow）

Workflow 1：
手动触发（或定时自动触发）Github Action 拉取 Google Sheet。
解析并输出 js 文件，更新 Repo 中相应的文件，并提交新 Commit。

-------

Workflow 2：
Google Sheet 设置为 Public - Read Only。
在前端 Tampermonkey 脚本中发起对 Google Sheet 的请求，将获取的 csv 格式 Playlist 数据
在前端解析和转换为 js 数组。
好处是更新 Google Sheet 后，无需额外地操作，用户可以立即获得最新的 Playlist 数据。

**Comment by jim60105** [comment]
這個提議不錯
我去看了下sheets api，它有使用限制存在，做Workflow 1會比2好

[ref](https://developers.google.com/sheets/api/limits)，雖然目前從client叫大概也不會超標

**Comment by jim60105** [comment]
目前編輯者只有我和 @LittleRice1007 ，我剛和他討論了下
我們兩人在線下純文字編輯上，比操作Google Sheet效率要高

這個題案我想先放著，未來有其它人要參與共編再討論是否實做

**Comment by jim60105** [comment]
我將此提案寫在了README，留待未來討論
